runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static/

_url: /.*
  script: auto

env_variables:
  TRAVELER_PW: Chopin9lives

beta_settings:
  cloud_sql_instances: wishlist-294814:us-central1:wishlist-db

